services:
  keyword-extractor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multilingual-keyword-extractor-api
    stdin_open: true
    tty: true

    volumes:
      - .:/app

    environment:
      - PYTHONUNBUFFERED=1

    ports:
      - "8000:8000"

    command: python api.py
